# Generated by Django 2.2 on 2019-04-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('britecoreapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='field_options',
            field=models.TextField(null=True),
        ),
    ]
