# Generated by Django 2.2 on 2019-04-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('britecoreapi', '0002_datafield_field_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
