# Generated by Django 2.2 on 2019-05-02 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('britecoreapi', '0003_auto_20190429_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacontent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='datacontent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='datacontent',
            name='row_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='row_contents', to='britecoreapi.DataTable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datacontent',
            name='field_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_contents', to='britecoreapi.DataField'),
        ),
        migrations.AlterField(
            model_name='datacontent',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_contents', to='britecoreapi.DataTable'),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='table_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_fields', to='britecoreapi.DataTable'),
        ),
        migrations.AlterUniqueTogether(
            name='datafield',
            unique_together={('table_id', 'name')},
        ),
        migrations.CreateModel(
            name='DataRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_rows', to='britecoreapi.DataTable')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='datafield',
            name='description',
        ),
    ]
